-- ISS-2026-302 corrective migration to 20260831270000, which is already applied.
--
-- WHY THIS FILE EXISTS RATHER THAN AN EDIT TO 20260831270000. That migration's header
-- described the durable-evidence half of this change as being produced by a
-- `lib/security/ip-restriction-gate.ts` calling `public.evaluate_ip_access` before each
-- business RPC. That component was deliberately not built, for the reason set out below, and
-- the header was written before that decision was final. An applied migration is never edited
-- (ADR-0027 Part C, AGENTS.md) -- not even a comment inside one, because the moment the file
-- stops being a byte-exact record of what the database ran, nobody can tell which parts of it
-- still are. So the correction lands here, and it lands as real DDL rather than as a note:
-- every one of the 65 functions 20260831270000 widened had no comment at all, and now says in
-- the schema itself that it is IP-gated and what that does and does not guarantee.
--
-- THE CORRECTION. There is no application-layer pre-check. A denial raised inside a business
-- transaction still loses its own app.ip_access_evaluations row when that transaction aborts
-- -- ISS-2026-307's residual, unchanged by widening the control from 5 functions to 70.
-- Postgres offers no in-transaction escape short of an autonomous transaction
-- (dblink/pg_background: a real new dependency and a new security surface) or having 65
-- business RPCs return a denial instead of raising one (a breaking contract change for every
-- caller). A pre-check from the application layer would produce the durable row, and costs an
-- extra database round trip on every finance approval and every HR decision to record evidence
-- for the rare denial. That trade is a judgement about latency against audit completeness, it
-- belongs to ISS-2026-307's own disposition, and smuggling it in as a side effect of the
-- wiring change would have made it invisible. What exists instead is an assertion:
-- scripts/db-tests/ip-restriction-network-access.sql pins the missing row as a property and
-- says in its own failure message that if it ever starts persisting the assertion must be
-- INVERTED, not deleted.
--
-- No function body, signature, grant or behaviour is changed here. Comments only.



comment on function app.activate_employee(p_master_record_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.activate_finance_account(p_account_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.add_ip_allowlist_entry(p_tenant_id uuid, p_raw_cidr text, p_label text, p_scope text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.approve_attendance_for_payroll_input(p_tenant_id uuid, p_from_date date, p_to_date date, p_employee_id uuid, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.approve_finance_correction(p_correction_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.approve_finance_exchange_rate(p_rate_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.approve_finance_invoice(p_invoice_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.approve_finance_journal(p_journal_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.approve_finance_period_reopen(p_lock_id uuid, p_expected_version integer, p_window_hours integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.approve_finance_settlement(p_settlement_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.approve_finance_tax_rule(p_rule_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.approve_finance_vendor_bill(p_bill_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.approve_leave_for_payroll_input(p_request_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.approve_timesheet_period_summary(p_summary_id uuid, p_expected_version integer, p_reason text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.certify_finance_reconciliation_run(p_run_id uuid, p_expected_version integer, p_reason text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.close_finance_period(p_period_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.create_finance_bank_account(p_tenant_id uuid, p_company_id uuid, p_account_name text, p_bank_name text, p_account_number_last4 text, p_currency text, p_gl_account_id uuid, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.decide_attendance_correction(p_request_id uuid, p_expected_version integer, p_decision text, p_decided_reason text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.decide_employee_position_assignment(p_assignment_id uuid, p_expected_version integer, p_decision text, p_reason text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.decide_overtime_request(p_request_id uuid, p_expected_version integer, p_decision text, p_decided_reason text, p_approved_minutes_override integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.decide_schedule_swap_request(p_request_id uuid, p_expected_version integer, p_decision text, p_decided_reason text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.decide_timesheet_entry(p_entry_id uuid, p_expected_version integer, p_decision text, p_decided_reason text, p_approved_minutes_override integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.discard_finance_settlement_draft(p_settlement_id uuid, p_expected_version integer, p_reason text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.execute_finance_settlement(p_settlement_id uuid, p_expected_version integer, p_execution_reference text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.generate_payroll_time_input(p_period_id uuid, p_employee_id uuid, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.generate_payroll_time_inputs_for_period(p_period_id uuid, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.import_historical_finance_journal(p_tenant_id uuid, p_company_id uuid, p_source_id uuid, p_journal_date date, p_currency text, p_lines jsonb, p_reason text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.issue_finance_invoice(p_invoice_id uuid, p_expected_version integer, p_issue_date date, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.lock_finance_period(p_tenant_id uuid, p_company_id uuid, p_period_id uuid, p_lock_scope text, p_reason text, p_evidence_ref text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.lock_timesheet_period(p_period_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.post_finance_correction(p_correction_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.post_finance_journal(p_journal_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.post_finance_opening_balance_batch(p_open_item_type text, p_open_item_id uuid, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.post_finance_settlement(p_settlement_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.post_finance_vendor_bill(p_bill_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.publish_attendance_policy_version(p_version_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.publish_finance_config_version(p_version_id uuid, p_actor_auth_user_id uuid, p_effective_from timestamp with time zone, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.publish_job_vacancy(p_id uuid, p_expected_version integer, p_validity_days integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.publish_leave_type(p_leave_type_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.publish_leave_type_policy_version(p_version_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.publish_onboarding_checklist_template_version(p_template_version_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.publish_overtime_policy_version(p_version_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.publish_roster_cycle(p_roster_cycle_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.publish_schedule_assignments(p_tenant_id uuid, p_from_date date, p_to_date date, p_org_unit_id uuid, p_employee_id uuid, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.publish_shift_template_version(p_version_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.record_direct_hire_approval(p_case_id uuid, p_expected_version integer, p_note text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.reject_timesheet_period_summary(p_summary_id uuid, p_expected_version integer, p_reason text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.release_finance_ap_hold(p_open_item_id uuid, p_expected_version integer, p_reason text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.release_finance_ar_hold(p_open_item_id uuid, p_expected_version integer, p_reason text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.relock_finance_period(p_lock_id uuid, p_expected_version integer, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.reopen_finance_period(p_period_id uuid, p_expected_version integer, p_reason text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.request_finance_receipt_deallocation(p_allocation_id uuid, p_reason text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.request_finance_settlement_reversal(p_settlement_id uuid, p_reason text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.request_ip_allowlist_bypass(p_tenant_id uuid, p_target_auth_user_id uuid, p_reason text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.request_mfa_exception(p_tenant_id uuid, p_target_auth_user_id uuid, p_reason text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.reverse_finance_ap_settlement(p_open_item_id uuid, p_amount numeric, p_reason text, p_source_type text, p_source_id uuid, p_idempotency_key text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.reverse_finance_ar_allocation(p_open_item_id uuid, p_amount numeric, p_reason text, p_source_type text, p_source_id uuid, p_idempotency_key text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.revoke_all_actor_sessions(p_tenant_id uuid, p_target_auth_user_id uuid, p_reason text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.revoke_ip_allowlist_entry(p_entry_id uuid, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.revoke_user_session(p_session_id uuid, p_reason text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.rollback_finance_config_version(p_target_version_id uuid, p_actor_auth_user_id uuid, p_reason text, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.set_finance_aging_bucket_config(p_tenant_id uuid, p_entity_type text, p_buckets jsonb, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.set_ip_allowlist_enforcement_mode(p_tenant_id uuid, p_enforcement_mode text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.set_mfa_tenant_policy(p_tenant_id uuid, p_tenant_wide_required boolean, p_required_layers jsonb, p_step_up_max_age_minutes integer, p_additional_high_risk_actions jsonb, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';

comment on function app.unmatch_finance_bank_transaction(p_transaction_id uuid, p_expected_version integer, p_reason text, p_actor_auth_user_id uuid, p_actor_label text, p_client_ip text) is
  'ISS-2026-302: IP-allowlist gated. Takes an optional trailing p_client_ip, checked after authority is established and before any state change, skipped when no address is supplied, and bypassable via an approved app.ip_allowlist_bypass_grants grant. This is defense in depth and an audit signal, NOT a boundary a caller cannot cross: a caller may simply omit the address. Authority remains the enforcement that cannot be omitted. A denial raised here aborts the transaction and takes its own app.ip_access_evaluations row with it (ISS-2026-307 residual).';
